pub fn generate_d_ts() -> String {
    r#"
/**
 * Fusillade Type Definitions
 * Auto-generated by `fusillade types`
 */

/// <reference no-default-lib="true"/>

/**
 * Global function to print messages to stdout (and worker logs).
 * @param msg The message to print.
 */
declare function print(msg: string): void;

/**
 * Global function to pause execution for a specified duration.
 * @param millis Duration in milliseconds.
 */
declare function sleep(millis: number): void;

/**
 * Reads a file from the filesystem.
 * @param path Path to the file.
 * @returns The content of the file as a string.
 */
declare function open(path: string): string;

/**
 * The current worker ID (0-based index).
 */
declare const __WORKER_ID: number;

/**
 * Environment variables.
 */
declare const __ENV: { [key: string]: string | undefined };

/**
 * Run a set of assertions on a value.
 * @param val The value to test.
 * @param checks An object where keys are assertion names and values are predicate functions.
 * @example
 * assertion(res.status, {
 *   "status is 200": (s) => s === 200
 * });
 */
declare function assertion(val: any, checks: { [name: string]: (val: any) => boolean }): void;

/**
 * Group metrics under a named segment.
 * @param name Name of the segment.
 * @param func Function to execute within the segment.
 */
declare function segment(name: string, func: () => void): void;

declare namespace http {
    interface HttpResponse {
        status: number;
        body: string;
        headers: { [name: string]: string };
    }

    interface HttpOptions {
        method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS";
        url: string;
        body?: string;
        headers?: { [name: string]: string };
        name?: string;
    }

    /**
     * Make an HTTP request.
     * @param opts Request options.
     */
    function request(opts: HttpOptions): HttpResponse;
}

declare namespace stats {
    interface StatsResult {
        p95: number;
        p99: number;
        avg: number;
        count: number;
        min: number;
        max: number;
    }

    /**
     * Get statistics for a named metric.
     * @param name Name of the metric (e.g. "http_req_duration").
     */
    function get(name: string): StatsResult;
}

declare namespace utils {
    function uuid(): string;
    function randomInt(min: number, max: number): number;
    function randomString(length: number): string;
    function randomItem<T>(arr: T[]): T | undefined;
}

declare namespace crypto {
    function md5(data: string): string;
    function sha1(data: string): string;
    function sha256(data: string): string;
}

declare namespace encoding {
    function b64encode(data: string): string;
    function b64decode(data: string): string;
}

declare class JsWebSocket {
    send(msg: string): void;
    recv(): string | null;
    close(): void;
}

declare namespace ws {
    function connect(url: string): JsWebSocket;
}

declare class JsMqttClient {
    constructor();
    connect(host: string, port: number, client_id: string): void;
    publish(topic: string, payload: string): void;
    close(): void;
}

declare class JsAmqpClient {
    constructor();
    connect(url: string): void;
    publish(exchange: string, routing_key: string, payload: string): void;
    close(): void;
}

declare class SharedArray<T = any> {
    constructor(name: string, factory: () => T[]);
    get(index: number): T;
    readonly length: number;
}

declare class GrpcClient {
    constructor();
    load(files: string[], includes: string[]): void;
    connect(url: string): Promise<void>;
    invoke(method: string, request: any): Promise<any>;
}
"#.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_d_ts() {
        let types = generate_d_ts();
        assert!(types.contains("declare namespace http"));
        assert!(types.contains("declare function print"));
        assert!(types.contains("declare class JsWebSocket"));
    }
}
